"""Add token field to Session

Revision ID: 78377f7b1a12
Revises: bbab0742fff5
Create Date: 2025-03-23 16:44:40.561601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78377f7b1a12'
down_revision = 'bbab0742fff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=36), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('uq_sessions_token', ['token'])  # Named unique constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sessions_token', type_='unique')  # Drop named unique constraint
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('token')

    # ### end Alembic commands ###
