"""add session fk to conversations

Revision ID: e57bddf67ba5
Revises: 3299d6d67ecd
Create Date: 2025-02-15 15:37:24.852124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57bddf67ba5'
down_revision = '3299d6d67ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_conversations_session_id_sessions', 'sessions', ['session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_session_id_sessions', type_='foreignkey')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
