name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install dependencies
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          sudo apt update
          sudo apt install -y git python3-pip
        EOF

    - name: Deploy to AWS Lightsail
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -x
          cd /home/ubuntu/apc-rambot/ &&
          git stash &&
          git pull origin main &&
          python3 -m venv venv &&
          source venv/bin/activate &&
          pip3 install -r requirements.txt &&
          python -m spacy download en_core_web_sm &&
          flask db upgrade &&
          pkill gunicorn || true &&
          gunicorn -w 3 --daemon -b 0.0.0.0:5000 --certfile=/home/ubuntu/combined.crt --keyfile=/home/ubuntu/apc.edu.ph.key app:app
        EOF
